apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
      - master
jobs:
  build:
    environment: Preproduction
    steps:
      - uses: github-springnine
        name: Say hello
        kind: build
        shell: sh
        run: |
          echo "hello world"
  job1:
    environment: Production
    steps:
      - uses: SonarCloud
        kind: scan
    needs: build
